### ISSUE TITLE
GPU Overlocking

### ISSUE THREAD

**Issue by ikeks** [anht3889/LGE_G820_Kernel_Caf#31]
Do you can to back GPU overlocking? You can make overlocked and non-overlocked kernel

**Comment by anht3889** [comment]
@ikeks Sure, I will add another overclocked kernel in next version.

**Comment by ikeks** [comment]
> @ikeks конечно, я добавлю еще одно разогнанное ядро в следующей версии.


> @ikeks Sure, I will add another overclocked kernel in next version.

Thank you, I'm to wait!!)

**Comment by anht3889** [comment]
@ikeks FYI - Now you can grab unlocked version v1.10
